name: AI智能调养机
url: https://ghj324.github.io

navigation:
  - title: 首页
    link: /
  - title: 体质辨识
    link: /constitution/
  - title: 点我自测
    link: /test/

collections:
  constitution_types:
    output: true
    permalink: /constitution/:path/

defaults:
  - scope:
      path: ""
      type: "constitution_types"
    values:
      layout: "constitution"

markdown: kramdown
